version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "task_L0"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
  nats:
    image: nats-streaming:latest
    ports:
      - "8222:8222"
      - "4222:4222"
